### ISSUE TITLE
Not responding on 8000

### ISSUE THREAD

**Issue by Valiantiam** [mchekin/rpg#39]
I tried to deploy and access remotely but it wont allow me to connect. I have it running on a headless ubuntu 18.04.

I confirmed I can reach the box and have updated the .env config and did a php artisan config:cache/clear

**Comment by mchekin** [comment]
@Valiantiam 

Sorry for not answering earlier. Just saw the issue.

Are you running in on Nginx or Apache server?
Or are you just using the `php artisan serve`?
